name: website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA254U4GKVKBZQFH5D
          aws-secret-access-key: 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
          aws-region: us-east-1
          
      - name: deploy website
        run: aws s3 sync . s3://manish123123 --delete --region us-east-1


   
